trailingComma: none
tabWidth: 4
semi: true
singleQuote: true
printWidth: 120
bracketSpacing: true
# in ts you have parenthesis for typed function params
arrowParens: always
quoteProps: consistent
bracketSameLine: true
proseWrap: preserve

vueIndentScriptAndStyle: true
