name: Test
on:
  pull_request:
    branches-ignore:
      - 'main'
      - 'patch/**'
  push:
    branches-ignore:
      - 'main'
      - 'patch/**'

jobs:
  tests:
    name: Run the tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm test
