name: Test
on:
  pull_request:
    branches-ignore:
      - 'main'
      - 'patch/**'
  push:
    branches-ignore:
      - 'main'
      - 'patch/**'

jobs:
  tests:
    name: Run the tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm install
      - run: npm test
      - run: npm run build
        env:
          NODE_OPTIONS: --openssl-legacy-provider

