name: Test Bump and Release Main
on:
  workflow_dispatch:
  push:
      branches:
        - 'main'
      paths:
        - '**.js'
        - '**.ts'
        - '**.vue'
        - '**.json'
        - '**.css'

jobs:
  tests:
    name: Ensure tests and builds are OK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run build
        env:
          NODE_OPTIONS: --openssl-legacy-provider
      - run: npm run build-storybook
        env:
          NODE_OPTIONS: --openssl-legacy-provider

  bump-and-publish:
    needs: [tests]
    name: 'Automated Version Bump'
    if: "success() && !startsWith(github.event.head_commit.message, 'chore: version bump')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bump
        if: success()
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          major-wording: 'BREAKING'
          default: 'minor'
          commit-message: 'chore: version bump to {{version}}'
      - uses: actions/setup-node@v4
        env:
          NODE_OPTIONS: --openssl-legacy-provider
        with:
          node-version: 18
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - name: Install
        run: npm ci
      - name: Publish
        run: npm publish
        env:
          NODE_OPTIONS: --openssl-legacy-provider
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build doc
        run: npm run build-storybook
        env:
          NODE_OPTIONS: --openssl-legacy-provider
      - name: Deploy doc to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}