name: Test Bump and Release Patch
on:
  push:
    branches:
      - 'patch/**'
    paths:
      - '**.js'
      - '**.ts'
      - '**.vue'
      - '**.json'
      - '**.css'
jobs:
  tests:
    name: Ensure tests and builds are OK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run build
        env:
          NODE_OPTIONS: --openssl-legacy-provider

  bump-and-publish:
    needs: [tests]
    name: 'Automated Version Bump'
    if: "success() && !startsWith(github.event.head_commit.message, 'chore: version bump')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          default: 'patch'
          commit-message: 'chore: version bump to {{version}}'
      - uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm ci
      - name: Publish
        run: npm publish
        env:
          NODE_OPTIONS: --openssl-legacy-provider
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}