name: Release
on:
  workflow_run:
    workflows: [Test and bump]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'chore: version bump')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
