name: Test and bump
on:
  push:
    branches:
      - '*'

jobs:
  tests:
    name: Run the tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm test
  bump:
    needs: [tests]
    name: 'Automated Version Bump'
    if: "success() && !startsWith(github.event.head_commit.message, 'chore: version bump') && github.ref_name == 'main'"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          major-wording: 'BREAKING'
          minor-wording: 'feat'
          patch-wording: 'fix,chore'
          commit-message: 'chore: version bump to {{version}}'

  publish:
    needs: [tests, bump]
    name: 'Release on NPM'
    runs-on: ubuntu-latest
    if: "success() && startsWith(github.event.head_commit.message, 'chore: version bump') && github.ref_name == 'main'"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: npm ci
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
